### ISSUE TITLE
Adding babel

### ISSUE THREAD

**Issue by bitboxer** [oefd/jsx-no-react#3]
In my branch I added babel to create a version of the library that can be used in other projects without transpiling the file. Which makes it way easier to add it in the default webpack build process. Are you interested in this?

Also I might add some tests and other functionality. I am using this in a side project of mine together with stimulusjs right now :) .

**Comment by bitboxer** [comment]
Pinging here just to see if you are interested. If not i will push my own version to npm under a new name. Currently writing a blockpost and would love for people to be able to try it out. Thanks!

**Comment by idletea** [comment]
Oh, sorry I missed that first message.

You're welcome to have the existing npm name / access honestly - as you may have noticed I haven't been actively developing it, and if you're interested in doing so by all means have at it!

**Comment by bitboxer** [comment]
That's very nice of you. Could you add bitboxer to the npm package so that I can update it?

**Comment by idletea** [comment]
No problem, and done. You should have the invite for write access.

**Comment by bitboxer** [comment]
Thanks for this!

**Comment by bitboxer** [comment]
I now pushed version `0.1.5` with me added as contributor and my fork as the base github branch. Will add more features and tests in the following weeks. But first I will be on a small vacation for a couple of weeks. Thanks again for handing this one over to me 🙇 .
